// @mustard/nunopi — 학습 모듈 배럴(client-safe, #889 배치2). server-only는 @mustard/nunopi/server.
export * from "./lib/translator/detectLanguage";
export * from "./lib/srs/activityLog";
export * from "./lib/srs/cardFrame";
export * from "./lib/srs/cardSource";
export * from "./lib/srs/collect";
export * from "./lib/srs/customDeck";
export * from "./lib/srs/deleteCard";
export * from "./lib/srs/due";
export * from "./lib/srs/schedule";
export * from "./lib/srs/stats";
export * from "./lib/srs/store";
export * from "./lib/cardChat";
export * from "./lib/cardDedup";
export * from "./lib/cardExplain";
export * from "./lib/collections";
export * from "./lib/deckAssign";
export * from "./lib/deckSelect";
export * from "./lib/exclusions";
export * from "./lib/exportHtml";
export * from "./lib/formatDuration";
export * from "./lib/highlightTerms";
export * from "./lib/historyDB";
export * from "./lib/isCommentLine";
export * from "./lib/memSession";
export * from "./lib/reanchorLines";
export * from "./lib/safeText";
export * from "./lib/history/collect";
export * from "./lib/history/context";
export * from "./lib/history/types";
export * from "./hooks/useCollapsed";
export * from "./hooks/useFullscreen";

// #889 배치3 컴포넌트+훅+context
export { default as AskSessionCards } from "./components/ask/AskSessionCards";
export * from "./components/ask/AskSessionCards";
export { default as AskView } from "./components/ask/AskView";
export * from "./components/ask/AskView";
export { default as AskSessionQuiz } from "./components/ask/AskSessionQuiz";
export * from "./components/ask/AskSessionQuiz";
export { default as AskChat } from "./components/ask/AskChat";
export * from "./components/ask/AskChat";
export { default as QuizRunner } from "./components/ask/QuizRunner";
export * from "./components/ask/QuizRunner";
export { default as AllCardsModal } from "./components/memorize/AllCardsModal";
export * from "./components/memorize/AllCardsModal";
export { default as CardSession } from "./components/memorize/CardSession";
export * from "./components/memorize/CardSession";
export { default as AgentDeckModal } from "./components/memorize/AgentDeckModal";
export * from "./components/memorize/AgentDeckModal";
export { default as CardExplainPanel } from "./components/memorize/CardExplainPanel";
export * from "./components/memorize/CardExplainPanel";
export { default as ActivityHeatmap } from "./components/memorize/ActivityHeatmap";
export * from "./components/memorize/ActivityHeatmap";
export { default as FlashCard } from "./components/memorize/FlashCard";
export * from "./components/memorize/FlashCard";
export { default as CardStageBar } from "./components/memorize/CardStageBar";
export * from "./components/memorize/CardStageBar";
export { default as AgentDeckHubModal } from "./components/memorize/AgentDeckHubModal";
export * from "./components/memorize/AgentDeckHubModal";
export { default as DeckFan } from "./components/memorize/DeckFan";
export * from "./components/memorize/DeckFan";
export { default as MemorizeInsights } from "./components/memorize/MemorizeInsights";
export * from "./components/memorize/MemorizeInsights";
export * from "./components/memorize/FlyCard";
export { default as HelpTooltip } from "./components/memorize/HelpTooltip";
export * from "./components/memorize/HelpTooltip";
export { default as CardInfoPanel } from "./components/memorize/CardInfoPanel";
export * from "./components/memorize/CardInfoPanel";
export { default as DeckSelect } from "./components/memorize/DeckSelect";
export * from "./components/memorize/DeckSelect";
export { default as MemModal } from "./components/memorize/MemModal";
export * from "./components/memorize/MemModal";
export { default as CardFan } from "./components/memorize/CardFan";
export * from "./components/memorize/CardFan";
export { default as GradePiles } from "./components/memorize/GradePiles";
export * from "./components/memorize/GradePiles";
export { default as MemorizeChat } from "./components/memorize/MemorizeChat";
export * from "./components/memorize/MemorizeChat";
export { default as CardDedupModal } from "./components/memorize/CardDedupModal";
export * from "./components/memorize/CardDedupModal";
export { default as CardBack } from "./components/memorize/CardBack";
export * from "./components/memorize/CardBack";
export { default as SessionDone } from "./components/memorize/SessionDone";
export * from "./components/memorize/SessionDone";
export { default as MemorizeView } from "./components/memorize/MemorizeView";
export * from "./components/memorize/MemorizeView";
export { default as DeckStatPicker } from "./components/memorize/DeckStatPicker";
export * from "./components/memorize/DeckStatPicker";
export { default as AgentAssignModal } from "./components/memorize/AgentAssignModal";
export * from "./components/memorize/AgentAssignModal";
export { default as MemorizeStats } from "./components/memorize/MemorizeStats";
export * from "./components/memorize/MemorizeStats";
export { default as ItTermSection } from "./components/learning/ItTermSection";
export * from "./components/learning/ItTermSection";
export { default as LineExplanationList } from "./components/learning/LineExplanationList";
export * from "./components/learning/LineExplanationList";
export { default as ItTermDictionary } from "./components/learning/ItTermDictionary";
export * from "./components/learning/ItTermDictionary";
export { default as LearningPanel } from "./components/learning/LearningPanel";
export * from "./components/learning/LearningPanel";
export { default as ChatRoom } from "./components/learning/ChatRoom";
export * from "./components/learning/ChatRoom";
export { default as ResizableBody } from "./components/learning/ResizableBody";
export * from "./components/learning/ResizableBody";
export { default as TokenSection } from "./components/learning/TokenSection";
export * from "./components/learning/TokenSection";
export { default as ItConceptSection } from "./components/learning/ItConceptSection";
export * from "./components/learning/ItConceptSection";
export * from "./components/learning/icons";
export { default as TokenDictionary } from "./components/learning/TokenDictionary";
export * from "./components/learning/TokenDictionary";
export { default as ConceptSection } from "./components/learning/ConceptSection";
export * from "./components/learning/ConceptSection";
export { default as CodeBlock } from "./components/learning/CodeBlock";
export * from "./components/learning/CodeBlock";
export { default as ConceptDictionary } from "./components/learning/ConceptDictionary";
export * from "./components/learning/ConceptDictionary";
export * from "./components/translator/AnalyzeControls";
export { default as AnalysisHistory } from "./components/translator/AnalysisHistory";
export * from "./components/translator/AnalysisHistory";
export { default as TextInputArea } from "./components/translator/TextInputArea";
export * from "./components/translator/TextInputArea";
export { default as EditorChatColumn } from "./components/translator/EditorChatColumn";
export * from "./components/translator/EditorChatColumn";
export { default as CodeInputArea } from "./components/translator/CodeInputArea";
export * from "./components/translator/CodeInputArea";
export { default as CodeEditor } from "./components/translator/CodeEditor";
export * from "./components/translator/CodeEditor";
export * from "./components/learning/conceptDescriptions";
export * from "./lib/analyze/AnalysisContext";
export * from "./hooks/useCodeAnalysis";

// newSessionId: cardChat·historyDB 동명 → 배럴 모호성 명시 해소(외부 미사용)
export { newSessionId } from "./lib/cardChat";
